[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/en/latest/"
  to = "/introduction/"
  status = 301

[[redirects]]
  from = "/install/install-node.html"
  to = "/getting-started/installing-the-cardano-node/"
  status = 301

[[redirects]]
  from = "/install/use-cli.html"
  to = "/getting-started/use-cli/"
  status = 301

[[redirects]]
  from = "/getting-started/stake-pool-operators/index.html"
  to = "/getting-started/operating-a-stake-pool/about-stake-pools/"
  status = 301

[[redirects]]
  from = "/getting-started/guidelines-for-operating-large-stake-pools/index.html/"
  to = "/getting-started/guidelines-for-large-spos/"
  status = 301

[[redirects]]
  from = "/getting-started/3rd-party-integration/index.html/"
  to = "/getting-started/integrating-with-third-parties/"
  status = 301

[[redirects]]
  from = "/getting-started/exchanges/index.html"
  to = "/getting-started/running-stake-pools-and-delegation-for-exchanges/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/what-is-a-blockchain.html"
  to = "/new-to-cardano/what-is-a-blockchain/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/what-is-a-cryptocurrency.html"
  to = "/new-to-cardano/what-is-a-cryptocurrency"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/why-use-cardano.html"
  to = "/new-to-cardano/why-use-cardano/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/proof-of-stake.html"
  to = "/new-to-cardano/proof-of-stake/"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/cardano-nodes.html"
  to = "/new-to-cardano/cardano-nodes"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/tools.html"
  to = "/new-to-cardano/cardano-tracking-tools/"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/how-to-purchase-ada.html"
  to = "/new-to-cardano/how-to-purchase-ada/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/types-of-wallets.html"
  to = "/new-to-cardano/types-of-wallets/"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/how-to-delegate.html"
  to = "/new-to-cardano/how-to-delegate/"
  status = 301

[[redirects]]
  from = "/getting-started-with-cardano/how-to-delegate.html"
  to = "/new-to-cardano/how-to-delegate/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/smart-contract-exp.html"
  to = "/new-to-cardano/what-is-a-smart-contract/"
  status = 301

[[redirects]]
  from = "/explore-cardano/what-is-a-cardano-node.html"
  to = "/core-concepts/cardano-node/"
  status = 301

[[redirects]]
  from = "/explore-cardano/what-is-a-stakepool.html"
  to = "/core-concepts/stake-pools/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-the-delegation-mechanism.html"
  to = "/core-concepts/delegation/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-pledging-and-rewards.html"
  to = "/core-concepts/pledging-rewards/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-pledging-and-rewards.html"
  to = "/core-concepts/pledging-rewards/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-pledging-and-rewards.html#distributing-rewards"
  to = "/pledging-rewards/#distributingrewards"
  status = 301

[[redirects]]
  from = "/learn/pledging-and-delegating-options.html"
  to = "/core-concepts/pledging-and-delegation-options/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-consensus.html"
  to = "/core-concepts/consensus-explained/"
  status = 301

[[redirects]]
  from = "/learn/Cardano-keys.html"
  to = "/core-concepts/cardano-keys/"
  status = 301

[[redirects]]
  from = "/learn/types-addresses.html"
  to = "/core-concepts/cardano-addresses/"
  status = 301

[[redirects]]
  from = "/explore-cardano/what-is-a-hard-fork-combinator.html"
  to = "/core-concepts/about-hard-forks/"
  status = 301

[[redirects]]
  from = "/learn/chain-confirmation-v-transaction-confirmation.html"
  to = "/core-concepts/chain-confirmation-versus-transaction-confirmation/"
  status = 301

[[redirects]]
  from = "/explore-cardano/design-rationale.html"
  to = "/explore-cardano/cardano-design-rationale/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-architecture-overview/index.html"
  to = "/explore-cardano/cardano-architecture/overview/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-network.html"
  to = "/explore-cardano/cardano-network/about-the-cardano-network/"
  status = 301

[[redirects]]
  from = "/explore-cardano/p2p-networking.html"
  to = "/explore-cardano/cardano-network/p2p-networking/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-monetary-policy.html"
  to = "/explore-cardano/monetary-policy/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-fee-structure.html"
  to = "/explore-cardano/fee-structure/"
  status = 301

[[redirects]]
  from = "/explore-cardano/further-reading.html"
  to = "/explore-cardano/resources/"
  status = 301

[[redirects]]
  from = "/explore-cardano/relevant-research-papers-and-specifications.html"
  to = "/explore-cardano/relevant-research-papers/"
  status = 301

[[redirects]]
  from = "/explorer.cardano.org/"
  to = "/tools/explorer/"
  status = 301

[[redirects]]
  from = "/projects/cardano-node/"
  to = "/cardano-components/cardano-node/"
  status = 301

[[redirects]]
  from = "https://github.com/input-output-hk/cardano-graphql#overview"
  to = "/cardano-components/cardano-graphql/"
  status = 301

[[redirects]]
  from = "https://github.com/input-output-hk/cardano-rosetta#cardano-rosetta"
  to = "/cardano-components/cardano-rosetta/"
  status = 301

[[redirects]]
  from = "https://github.com/input-output-hk/cardano-ledger-specs#cardano-ledger"
  to = "/cardano-components/cardano-ledger-specs/"
  status = 301

[[redirects]]
  from = "https://github.com/input-output-hk/cardano-db-sync#cardano-db-sync"
  to = "/cardano-components/cardano-db-sync/"
  status = 301

[[redirects]]
  from = "https://github.com/input-output-hk/cardano-wallet#overview"
  to = "/cardano-components/cardano-wallet/"
  status = 301
