[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/en/latest/"
  to = "/introduction/"
  status = 301

[[redirects]]
  from = "/install/install-node.html"
  to = "/getting-started/installing-the-cardano-node/"
  status = 301